{
   genubflookup, generates a unsigned byte to float color lookup table (ubflookup.inc)
   Copyright (C) 2011. Dejan Boras
}

{$INCLUDE oxheader.inc}
PROGRAM genubflookup;

   USES sysutils, uSimpleParser;

VAR
   p: TParseData;

function parse(var f: text): boolean;
var
   i: longint;

begin
   result := true;
   writeln(f, '{');
   writeln(f, #9+'File generated by genubflookup on: ', DateToStr(Date()));
   writeln(f, #9+'This file is part of the oX engine.');
   writeln(f);
   writeln(f, #9+'This table is used to quickly look up floating point values when converting a');
   writeln(f, #9+'unsigned byte (0 .. 255) color value to floating point (0.0 .. 1.0).');
   writeln(f, '}');
   writeln(f);
   writeln(f, 'oxUBtoFLookup: array[0..255] of single = (');
   for i := 0 to 255 do begin
      write(f, #9+'{', i, '}', 1 / 255 * i);
      if(i < 255) then 
         writeln(f, ',')
      else 
         writeln(f);
   end;
   writeln(f, ');');
end;
   
BEGIN
   ParseInitWrite(p, @parse);
   ParseWriteFile('ubflookup.inc', p);
END.
