{
   oxeduEditRenderers, oxed edit window renderers
   Copyright (C) 2017. Dejan Boras
}

{$INCLUDE oxheader.inc}
UNIT oxeduComponentGlyph;

INTERFACE

   USES
      uStd, uColors,
      {ox}
      oxuComponent, oxuTexture, oxuDefaultTexture, oxuResourcePool,
      {oxed}
      oxeduIcons;

TYPE
   oxedPComponentGlyph = ^oxedTComponentGlyph;

   { oxedTComponentGlyph }

   oxedTComponentGlyph = record
      Component: oxTComponentType;
      Name: string;
      Code: loopint;
      {glyph texture associated with this entity}
      Texture: oxTTexture;
      Color: TColor4ub;

      procedure Initialize(out glyph: oxedTComponentGlyph);

      procedure CreateTexture();

      {destroy texture}
      procedure Destroy();
   end;

VAR
   oxedGlyphTextureSize: loopint;

IMPLEMENTATION

{ oxedTComponentGlyph }

procedure oxedTComponentGlyph.Initialize(out glyph: oxedTComponentGlyph);
begin
   ZeroPtr(@glyph, SizeOf(glyph));
   glyph.Color := cWhite4ub;
end;


procedure oxedTComponentGlyph.CreateTexture();
begin
   if(Texture = nil) then begin
      {generate a texture by glyph name}
      if(Name <> '') then
         Texture := oxedIcons.Create(Name, oxedGlyphTextureSize);

      {next try using code if nothing generated by name}
      if(Code <> 0) and ((Texture = nil) or (Texture = oxDefaultTexture.Texture)) then
           Texture := oxedIcons.Create(Code, oxedGlyphTextureSize);
   end;
end;

procedure oxedTComponentGlyph.Destroy();
begin
   oxResource.Destroy(Texture);
end;

INITIALIZATION
   oxedGlyphTextureSize := 64;

END.
