{
   android_view
   Copyright (c) 2020. Dejan Boras
}

UNIT android_view;

INTERFACE

CONST
   SYSTEM_UI_FLAG_VISIBLE = 0;
   SYSTEM_UI_FLAG_LOW_PROFILE = $1;
   SYSTEM_UI_FLAG_HIDE_NAVIGATION = $2;
   SYSTEM_UI_FLAG_FULLSCREEN = $4;
   SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR = $10;
   SYSTEM_UI_FLAG_LAYOUT_STABLE = $100;
   SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION = $200;
   SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN = $400;
   SYSTEM_UI_FLAG_IMMERSIVE = $800;
   SYSTEM_UI_FLAG_IMMERSIVE_STICKY = $1000;
   SYSTEM_UI_FLAG_LIGHT_STATUS_BAR = $2000;

   SYSTEM_UI_LAYOUT_FLAGS = $600;

   STATUS_BAR_VISIBLE = 0;
   STATUS_BAR_HIDDEN = 1;

IMPLEMENTATION

END.
